services:
  DotnetExam.ClickHouse:
    image: clickhouse/clickhouse-server:latest
    container_name: DotnetExam_ClickHouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 18123:8123
      - 9000:9000
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=password
    volumes:
      - clickhouse_data:/var/lib/clickhouse/


volumes:
    clickhouse_data:

